version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mongodb_network
    volumes:
      - mongodb_volume:/data/db
    ports:
      - "27017:27017"

  back_server:
    image: thomaspsl/back_server:1.0.0
    container_name: back_server
    build:
      context: ./back-server
      dockerfile: Dockerfile
    networks:
      - mongodb_network
      - front_network
    environment:
      MONGO_URL: mongodb://mongodb:27017
    ports:
      - "5000:8081"
  
  front_client:
    image: thomaspsl/front_client:1.0.0
    container_name: front_client
    build:
      context: ./front-client
      dockerfile: Dockerfile
    networks:
      - front_network
    depends_on:
      - back_server
    ports:
      - "4000:80"
    
volumes:
  mongodb_volume:
    name: mongodb_volume
    driver: local

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge
  front_network:
    name: front_network
    driver: bridge